version: "3.3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "twitch_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "testdb123"
      MYSQL_ROOT_PASSWORD: "testdb123"
    ports:
      - "3306:3306"
    expose:
      - "3306"

    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
